export const styles = {
  container: {
    textAlign: "center",
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: "#E3F2FD",
    margin: "0 auto",
    maxWidth: "100%",
    height: "100vh",
    position: "relative",
    backgroundImage: "url('/backgroundimg.jpeg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundAttachment: "fixed"
  },
  overlay: {
    content: '""',
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0, 0.5)",
  },
  title: {
    fontSize: "50px",
    fontWeight: "700",
    color: "#ffffff",
    margin: "15px 0",
    textAlign: "center",
    cursor: "pointer",
  },
  navbar: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "40px",
    gap: "60px",
  },
  navLink: {
    textDecoration: "none",
    fontSize: "20px",
    color: "#ffffff",
    fontWeight: "500",
  },
  mainContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "200px 20px",
    margin: "auto",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  subtitle: {
    fontSize: "50px",
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: "10px",
  },
  description: {
    fontSize: "16px",
    color: "#ffffff",
    marginBottom: "30px",
    lineHeight: "1.5",
  },
  dynamicMessage: {
    fontSize: "18px",
    color: "Black",
    marginBottom: "20px",
  },
  uploadButton: {
    padding: "12px 24px",
    fontSize: "16px",
    fontWeight: "bold",
    backgroundColor: "#f74b4b",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginTop: "20px",
    transition: "all 0.3s ease",
    width: "fit-content",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "8px",
  },
  progressBarContainer: {
    marginTop: "20px",
    width: "80%",
    height: "5px",
    backgroundColor: "#e0e0e0",
    borderRadius: "5px",
    overflow: "hidden",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  progressBar: {
    width: "100%",
    height: "5px",
    backgroundColor: "orange",
    animation: "progress 1.5s infinite",
  },
  resultBox: {
    padding: "10px",
    backgroundColor: "#fff3e0",
    border: "1px solid #ffcc80",
    borderRadius: "10px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
  },
  overallConditionBox: {
    marginBottom: "20px",
    padding: "20px",
    backgroundColor: "#4caf50", // Calming green
    borderRadius: "15px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    textAlign: "center",
    border: "1px solid #388e3c",
  },
  overallConditionTitle: {
    fontSize: "26px",
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: "10px",
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  overallCondition: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#ffffff",
  },
  resultDetails: {
    textAlign: "center",
    padding: "15px",
    backgroundColor: "#e8f5e9",
    borderRadius: "10px",
    boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
    marginBottom: "15px",
  },
  detailTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#2e7d32",
    marginBottom: "10px",
  },
  resultDetails: {
    textAlign: "center",
    padding: "10px",
  },
  resultSection: {
    marginBottom: "15px",
  },
  detailTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#f74b4b",
    marginTop: "5px",
  },
  resultFooter: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    maxWidth: "60%",
    width: "100%",
  },
  newReturnButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "8px",
    marginTop: "20px",
    padding: "12px 24px",
    fontSize: "16px",
    fontWeight: "bold",
    backgroundColor: "#4caf50",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    width: "fit-content",
  },
};
